name: CI Workflow

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install linter
        run: |
          pip install pylint

      - name: Run linter
        run: |
          cd python-fast-app
          pylint **/*.py

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd python-fast-app
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          cd python-fast-app
          pytest --maxfail=1 --disable-warnings -q

